
-- ******* Run This file to get authorization of INSURANCEAPP schema *******

-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('select','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('update','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('insert','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('delete','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('all','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('create any','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('alter','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('drop','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('execute','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('trigger','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('index','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('debug','INSURANCEAPP','SYSTEM');
-- call _SYS_REPO.GRANT_SCHEMA_PRIVILEGE_ON_ACTIVATED_CONTENT('references','INSURANCEAPP','SYSTEM');
 
grant select on schema INSURANCEAPP to _SYS_REPO with grant option;

